<?xml version="1.0" encoding="utf-8"?>
<Project>

    <PropertyGroup>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)stylecop.ruleset</CodeAnalysisRuleSet>
        <EnableNETAnalyzers>false</EnableNETAnalyzers>
        <AnalysisMode>AllEnabledByDefault</AnalysisMode>
        <AnalysisLevel>9.0</AnalysisLevel>
        <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
        <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
        <WarningsNotAsErrors>NU1901;NU1902;NU1903;NU1904</WarningsNotAsErrors>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    </PropertyGroup>

    <ItemGroup>
        <AdditionalFiles Include="$(MSBuildThisFileDirectory)\stylecop.json" Link="stylecop.json" />
        <PackageReference Include="StyleCop.Analyzers" ExcludeAssets="All" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
      <SonarQubeSetting Include="sonar.cpd.exclusions">
        <Value>**/**</Value>
      </SonarQubeSetting>
    </ItemGroup>

</Project>