<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>6c8a1c5c-436d-4fa5-9c07-f2c7879f1a9c</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/MedCore.Auth.IdentityServer/MedCore.Auth.IdentityServer.csproj" />
    <ProjectReference Include="..\..\src\MedCore.DatabaseMigrationJob\MedCore.DatabaseMigrationJob.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.Sql" Version="13.2.4" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.2.4" />
  </ItemGroup>

</Project>
